APP_NAME = "AstroDodge"

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 360
DISPLAY_SCALE = 2
FPS = 60

DEFAULT_FONT = "assets\\fonts\\EchoesOfZyra.ttf"
IMGS_DIR = "assets\\imgs\\"
SFX_DIR = "assets\\sfx\\"
MUSIC_DIR = "assets\\music\\"
VERTEX_SHADER = "vertex_shader"
FRAGMENT_SHADER1 = "fragment_shader"
FRAGMENT_SHADER2 = "post_processing"

TRANSITION_SPEED = 0.05

LEVEL_INCREASE_SPEED = 0.001
MAX_LEVEL = 4

PLAYER_VELOCITY = 3
MAX_ROTATION_SPEED = 5
BULLET_SPEED = 5
SHOOTING_INTERVAL = 0.3

ASTEROID_MIN_SCALE = 1.0
ASTEROID_MAX_SCALE = 2.5
ASTEROID_MIN_SPEED = 1
ASTEROID_MAX_SPEED = 4
ASTEROID_SPAWN_INTERVAL = 3
OUTSIDE_MARGIN = 60

SCORE = 100
SHAKE = 15
GLITCH = 0.05

PARTICLE_LIFETIME = 3
PARTICLE_VELOCITY = 0
PARTICLE_AMOUNT = 50

ANIMATION_SPEED = 0.3

# UI settings
SHOOTING_BAR_WIDTH = 50
SHOOTING_BAR_HEIGHT = 10

# Testing
LEVEL = 1
