SCREEN_WIDTH = 640
SCREEN_HEIGHT = 360
DISPLAY_SCALE = 2
FPS = 60

DEFAULT_FONT = "assets/fonts/EchoesOfZyra.ttf"
IMGS_DIR = "assets/imgs/"
SFX_DIR = "assets/sfx/"
MUSIC_DIR = "assets/music/"

PLAYER_SPEED = 3
BULLET_SPEED = 5
SHOOTING_INTERVAL = 0.5

ASTEROID_MIN_SIZE = 10
ASTEROID_MAX_SIZE = 20
ASTEROID_MIN_SPEED = 2
ASTEROID_MAX_SPEED = 5
ASTEROID_SPAWN_INTERVAL = 3
ASTEROID_SPAWN_AREA = 40

SHAKE = 3

PARTICLE_LIFETIME = 3
PARTICLE_VELOCITY = 5
PARTICLE_AMOUNT = 20
