SCREEN_WIDTH = 640
SCREEN_HEIGHT = 360
DISPLAY_SCALE = 2
FPS = 60

DEFAULT_FONT = "assets/fonts/EchoesOfZyra.ttf"
IMGS_DIR = "assets/imgs/"
SFX_DIR = "assets/sfx/"
MUSIC_DIR = "assets/music/"

PLAYER_SPEED = 3
BULLET_SPEED = 5
SHOOTING_INTERVAL = 0.6

ASTEROID_MIN_SCALE = 1.0
ASTEROID_MAX_SCALE = 2.5
ASTEROID_MIN_SPEED = 1
ASTEROID_MAX_SPEED = 4
ASTEROID_SPAWN_INTERVAL = 3
ASTEROID_SPAWN_AREA = 40

SHAKE = 15

PARTICLE_LIFETIME = 3
PARTICLE_VELOCITY = 0
PARTICLE_AMOUNT = 20

ANIMATION_SPEED = 0.3
